// ReportsPage.js - Comprehensive Reports Management Component for Super Admin
import React, { useState, useEffect } from 'react';
import { jsPDF } from 'jspdf';
import { motion, AnimatePresence } from 'framer-motion';
import { Download, FileText, Filter, Search, Calendar, Clock,CheckCircle,ChevronDown, TrendingUp, Activity, Zap, Shield, Plus, Edit, Trash2 } from 'lucide-react';

const ReportsPage = () => {
  const [reports, setReports] = useState([]);
  const [filteredReports, setFilteredReports] = useState([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [filterType, setFilterType] = useState('All');
  const [sortBy, setSortBy] = useState('date'); // date, title, type
  const [sortOrder, setSortOrder] = useState('desc'); // asc, desc
  const [isGenerating, setIsGenerating] = useState(false);
  const [showForm, setShowForm] = useState(false);
  const [newReport, setNewReport] = useState({ title: '', date: '', type: 'PDF' });

  // Mock reports data (aggregated from system data)
  useEffect(() => {
    // Simulate API fetch
    setTimeout(() => {
      const mockReports = [
        { id: 1, title: 'Monthly Energy Report - December 2025', date: '2025-12-01', type: 'PDF', status: 'Generated', size: '2.5 MB', generatedBy: 'System' },
        { id: 2, title: 'Quarterly Efficiency Analysis - Q4 2025', date: '2025-10-01', type: 'Excel', status: 'Generated', size: '1.8 MB', generatedBy: 'Admin' },
        { id: 3, title: 'Annual Carbon Impact Summary - 2025', date: '2025-01-01', type: 'PDF', status: 'Generated', size: '3.2 MB', generatedBy: 'System' },
        { id: 4, title: 'Device Health Overview - November 2025', date: '2025-11-15', type: 'PDF', status: 'Generating', size: '-', generatedBy: 'Admin' },
        { id: 5, title: 'Alert Summary Report - Q4 2025', date: '2025-10-01', type: 'CSV', status: 'Generated', size: '0.8 MB', generatedBy: 'System' },
        { id: 6, title: 'Production Forecast - 2026', date: '2025-12-17', type: 'Excel', status: 'Generated', size: '2.1 MB', generatedBy: 'Admin' }
      ];
      setReports(mockReports);
      setFilteredReports(mockReports);
    }, 500);
  }, []);

  // Filter and search reports
  useEffect(() => {
    let filtered = [...reports];

    // Search
    if (searchTerm) {
      filtered = filtered.filter(report =>
        report.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
        report.generatedBy.toLowerCase().includes(searchTerm.toLowerCase())
      );
    }

    // Filter by type
    if (filterType !== 'All') {
      filtered = filtered.filter(report => report.type === filterType);
    }

    // Sort
    filtered.sort((a, b) => {
      let aVal, bVal;
      switch (sortBy) {
        case 'date':
          aVal = new Date(a.date);
          bVal = new Date(b.date);
          break;
        case 'title':
          aVal = a.title;
          bVal = b.title;
          break;
        case 'type':
          aVal = a.type;
          bVal = b.type;
          break;
        default:
          return 0;
      }
      return sortOrder === 'asc' ? (aVal > bVal ? 1 : -1) : (aVal < bVal ? 1 : -1);
    });

    setFilteredReports(filtered);
  }, [searchTerm, filterType, sortBy, sortOrder, reports]);

  const handleSort = (field) => {
    if (sortBy === field) {
      setSortOrder(sortOrder === 'asc' ? 'desc' : 'asc');
    } else {
      setSortBy(field);
      setSortOrder('desc');
    }
  };

  const handleDownload = (report) => {
    // Simulate download with PDF generation for demo
    if (report.type === 'PDF') {
      const doc = new jsPDF();
      doc.text(`${report.title} - Generated on ${new Date().toLocaleDateString()}`, 10, 10);
      doc.text(`Status: ${report.status}`, 10, 20);
      doc.text(`Size: ${report.size}`, 10, 30);
      doc.text(`Generated by: ${report.generatedBy}`, 10, 40);
      doc.save(`${report.title.replace(/ /g, '_')}.pdf`);
    } else {
      alert(`Downloading ${report.title} as ${report.type}...`);
    }
  };

  const generateNewReport = () => {
    setIsGenerating(true);
    setTimeout(() => {
      const newId = reports.length + 1;
      const generatedReport = {
        id: newId,
        title: newReport.title || 'Custom Report',
        date: newReport.date || new Date().toISOString().split('T')[0],
        type: newReport.type,
        status: 'Generated',
        size: '1.2 MB',
        generatedBy: 'Admin'
      };
      setReports(prev => [...prev, generatedReport]);
      setNewReport({ title: '', date: '', type: 'PDF' });
      setShowForm(false);
      setIsGenerating(false);
      alert('Report generated successfully!');
    }, 2000);
  };

  const deleteReport = (id) => {
    setReports(prev => prev.filter(r => r.id !== id));
  };

  // Analytics
  const totalReports = filteredReports.length;
  const pdfCount = filteredReports.filter(r => r.type === 'PDF').length;
  const excelCount = filteredReports.filter(r => r.type === 'Excel').length;
  const csvCount = filteredReports.filter(r => r.type === 'CSV').length;
  const generatedCount = filteredReports.filter(r => r.status === 'Generated').length;

  return (
    <div className="bg-gray-100 min-h-screen p-6">
      <motion.h1 
        initial={{ opacity: 0, y: -20 }} 
        animate={{ opacity: 1, y: 0 }} 
        className="text-3xl font-bold mb-8 text-gray-900 flex items-center gap-3"
      >
        <FileText size={32} className="text-blue-500" />
        Super Admin: Reports Management
      </motion.h1>

      {/* Analytics Overview */}
      <div className="grid grid-cols-1 md:grid-cols-5 gap-4 mb-6">
        <div className="bg-white p-4 rounded-xl border border-gray-200 shadow-sm">
          <div className="flex items-center gap-2 mb-2">
            <FileText size={20} className="text-blue-600" />
          </div>
          <p className="text-xs text-gray-500">Total Reports</p>
          <p className="text-2xl font-bold text-gray-900">{totalReports}</p>
        </div>
        <div className="bg-white p-4 rounded-xl border border-gray-200 shadow-sm">
          <div className="flex items-center gap-2 mb-2">
            <Download size={20} className="text-green-600" />
          </div>
          <p className="text-xs text-gray-500">PDF</p>
          <p className="text-2xl font-bold text-green-600">{pdfCount}</p>
        </div>
        <div className="bg-white p-4 rounded-xl border border-gray-200 shadow-sm">
          <div className="flex items-center gap-2 mb-2">
            <TrendingUp size={20} className="text-yellow-600" />
          </div>
          <p className="text-xs text-gray-500">Excel</p>
          <p className="text-2xl font-bold text-yellow-600">{excelCount}</p>
        </div>
        <div className="bg-white p-4 rounded-xl border border-gray-200 shadow-sm">
          <div className="flex items-center gap-2 mb-2">
            <Activity size={20} className="text-purple-600" />
          </div>
          <p className="text-xs text-gray-500">CSV</p>
          <p className="text-2xl font-bold text-purple-600">{csvCount}</p>
        </div>
        <div className="bg-white p-4 rounded-xl border border-gray-200 shadow-sm">
          <div className="flex items-center gap-2 mb-2">
            <CheckCircle size={20} className="text-teal-600" />
          </div>
          <p className="text-xs text-gray-500">Generated</p>
          <p className="text-2xl font-bold text-teal-600">{generatedCount}</p>
        </div>
      </div>

      {/* Controls */}
      <div className="bg-white rounded-xl border border-gray-200 p-6 mb-6">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4 items-center">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" size={18} />
            <input
              type="text"
              placeholder="Search reports..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="pl-10 pr-4 py-2 w-full border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
          </div>
          <select
            value={filterType}
            onChange={(e) => setFilterType(e.target.value)}
            className="px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
          >
            <option value="All">All Types</option>
            <option value="PDF">PDF</option>
            <option value="Excel">Excel</option>
            <option value="CSV">CSV</option>
          </select>
          <div className="flex flex-wrap gap-2">
            {['date', 'title', 'type'].map(field => (
              <button
                key={field}
                onClick={() => handleSort(field)}
                className={`px-3 py-1 text-xs rounded-full border font-medium flex items-center gap-1 ${
                  sortBy === field
                    ? sortOrder === 'desc'
                      ? 'bg-blue-100 text-blue-700 border-blue-300'
                      : 'bg-blue-100 text-blue-700 border-blue-300 rotate-180'
                    : 'bg-white text-gray-500 border-gray-300 hover:bg-gray-50'
                }`}
              >
                {field.charAt(0).toUpperCase() + field.slice(1)}
                {sortBy === field && <ChevronDown size={12} className={sortOrder === 'asc' ? 'rotate-180' : ''} />}
              </button>
            ))}
          </div>
          <button
            onClick={() => setShowForm(!showForm)}
            className="px-4 py-2 bg-blue-600 text-white rounded-lg font-medium hover:bg-blue-700 flex items-center gap-2 ml-auto"
          >
            <Plus size={16} />
            Generate Report
          </button>
        </div>
      </div>

      {/* Generate New Report Form */}
      <AnimatePresence>
        {showForm && (
          <motion.div
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
            className="bg-white rounded-xl border border-gray-200 p-6 mb-6"
          >
            <h3 className="text-lg font-semibold text-gray-900 mb-4">Generate New Report</h3>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <input
                type="text"
                placeholder="Report Title"
                value={newReport.title}
                onChange={(e) => setNewReport({ ...newReport, title: e.target.value })}
                className="px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
              <input
                type="date"
                value={newReport.date}
                onChange={(e) => setNewReport({ ...newReport, date: e.target.value })}
                className="px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
              <select
                value={newReport.type}
                onChange={(e) => setNewReport({ ...newReport, type: e.target.value })}
                className="px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
              >
                <option value="PDF">PDF</option>
                <option value="Excel">Excel</option>
                <option value="CSV">CSV</option>
              </select>
            </div>
            <div className="flex gap-2 mt-4">
              <button
                onClick={generateNewReport}
                disabled={isGenerating}
                className="px-4 py-2 bg-green-600 text-white rounded-lg font-medium hover:bg-green-700 disabled:opacity-50 flex items-center gap-2"
              >
                {isGenerating ? <Clock size={16} className="animate-spin" /> : <TrendingUp size={16} />}
                Generate
              </button>
              <button
                onClick={() => setShowForm(false)}
                className="px-4 py-2 bg-gray-300 text-gray-700 rounded-lg font-medium hover:bg-gray-400"
              >
                Cancel
              </button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Reports List */}
      <div className="bg-white rounded-xl border border-gray-200 shadow overflow-hidden">
        <div className="overflow-y-auto max-h-[60vh]">
          <AnimatePresence>
            {filteredReports.map(report => (
              <motion.div
                key={report.id}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -20 }}
                className="p-6 border-b border-gray-100 hover:bg-gray-50 transition-colors"
              >
                <div className="flex items-start justify-between">
                  <div className="flex-1">
                    <div className="flex items-start gap-3">
                      <div className="flex-shrink-0">
                        {report.type === 'PDF' && <FileText size={24} className="text-blue-600 mt-1" />}
                        {report.type === 'Excel' && <Activity size={24} className="text-green-600 mt-1" />}
                        {report.type === 'CSV' && <TrendingUp size={24} className="text-purple-600 mt-1" />}
                      </div>
                      <div className="flex-1 min-w-0">
                        <h4 className="font-semibold text-gray-900 truncate">{report.title}</h4>
                        <p className="text-sm text-gray-500 mt-1 flex items-center gap-2">
                          <Calendar size={14} />
                          {report.date} • {report.type} • {report.size} • {report.generatedBy}
                        </p>
                        <span className={`inline-flex px-2 py-1 text-xs font-medium rounded-full ${
                          report.status === 'Generated' ? 'bg-green-100 text-green-800' : 'bg-yellow-100 text-yellow-800'
                        } mt-2`}>
                          {report.status}
                        </span>
                      </div>
                    </div>
                  </div>
                  <div className="flex items-center gap-2 ml-4 flex-shrink-0">
                    <button
                      onClick={() => handleDownload(report)}
                      className="p-2 text-blue-600 hover:text-blue-800 rounded-lg hover:bg-blue-50 transition-colors"
                      title="Download"
                    >
                      <Download size={18} />
                    </button>
                    <button
                      onClick={() => {/* Edit functionality */ alert('Edit report')}}
                      className="p-2 text-gray-500 hover:text-gray-700 rounded-lg hover:bg-gray-50 transition-colors"
                      title="Edit"
                    >
                      <Edit size={18} />
                    </button>
                    <button
                      onClick={() => deleteReport(report.id)}
                      className="p-2 text-red-500 hover:text-red-700 rounded-lg hover:bg-red-50 transition-colors"
                      title="Delete"
                    >
                      <Trash2 size={18} />
                    </button>
                  </div>
                </div>
              </motion.div>
            ))}
          </AnimatePresence>
        </div>
      </div>

      {/* Empty State */}
      {filteredReports.length === 0 && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="text-center py-12 bg-white rounded-xl border border-gray-200 shadow"
        >
          <FileText size={48} className="mx-auto mb-4 text-gray-400" />
          <h3 className="text-lg font-medium text-gray-900 mb-2">No Reports Found</h3>
          <p className="text-gray-500 mb-4">Try adjusting your search or filters, or generate a new report.</p>
          <button
            onClick={() => setShowForm(true)}
            className="px-4 py-2 bg-blue-600 text-white rounded-lg font-medium hover:bg-blue-700 flex items-center gap-2 mx-auto"
          >
            <Plus size={16} />
            Generate First Report
          </button>
        </motion.div>
      )}
    </div>
  );
};

export default ReportsPage;